---
title: >
  `r params$title`
params:
  email: bdbest@gmail.com
  date: 2021-05-26 08:57:39 UTC
  title: test 2 inxns
  filetype: html
  contents:
    value:
      projects: no
      management: yes
  interactions:
    value:
    - - Receptor.Fish
      - Stressor.PhysicalInteraction.Collision
      - Technology.Wave
    - - Receptor.MarineMammals
      - Stressor.Noise
      - Technology.Wave
  document_checks:
    value:
    - ck_ixn
    - ck_mp
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    number_sections: true
    mathjax: null
    css: "/share/github/apps_dev/report-v2/www/styles.css"
  pdf_document:
    toc: true
    toc_depth: 4
    number_sections: true
    #keep_md: yes
    latex_engine: xelatex
  word_document:
    toc: true
    toc_depth: 4
    number_sections: true
    #keep_md: yes
editor_options: 
  chunk_output_type: console
always_allow_html: true # install.packages("webshot"); webshot::install_phantomjs()
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, warning = F, message = F, eval = T)
# for interactive debug: 
# params <- knitr::knit_params(readLines("{{rmd}}"))
# params$contents        <- params$contents$value
# params$interactions    <- params$interactions$value
# params$document_checks <- params$document_checks$value

```

```{r init}
source("/share/github/apps_dev/scripts/common.R")
source(file.path(dir_scripts, "db.R"))
source(file.path(dir_scripts, "shiny_report.R"))
source("/share/github/api/scripts/report.R")
```

# Configuration

```{r, comment=""}
list(params) %>% yaml::as.yaml() %>% cat()
```
